module.exports = function(h) {
const { titleBlock, spacer, twoCol, h1, h2, h3, body, bullet, numbered, code, infoBox, evalTable, schemaTable, endpointTable, divider, PageBreak, Paragraph, TextRun, C, AlignmentType, ShadingType } = h;
return [
...titleBlock(), spacer(240),
twoCol([["FIELD","DETAILS"],["Project Name","RAG-Based Document Q&A System with Analytics Dashboard"],["Client / Assignment","Vestaff — Junior AI Developer Task"],["Document Type","Product Requirements Document (PRD)"],["Version","1.0"],["Status","Ready for Development"],["Prepared Date","June 2026"],["Source Document","AWS Customer Agreement (aws.amazon.com/agreement)"],["Submission Deadline","48 hours from task receipt"]],2500,6860),
spacer(320), new Paragraph({children:[new PageBreak()]}),
h1("1. Executive Summary"),
body("This PRD defines the complete requirements for a Retrieval-Augmented Generation (RAG) system designed as a Junior AI Developer assignment from Vestaff. The system enables natural language question-answering over the AWS Customer Agreement PDF, exposes a RESTful FastAPI backend with full SQL usage logging, and surfaces insights through a live analytics dashboard."),
spacer(80), body("The deliverable consists of three integrated layers:"),
bullet("RAG Pipeline — PDF ingestion, chunking, embedding, vector storage, and LLM-powered answer generation"),
bullet("FastAPI Backend — Three endpoints with Pydantic validation, error handling, and SQLite/PostgreSQL logging"),
bullet("Frontend Dashboard — Streamlit or React/Next.js UI with a chat interface and an analytics view"),
spacer(120),
infoBox("EVALUATION WEIGHT SUMMARY","RAG Pipeline Design (20%)  |  FastAPI Backend & SQL (20%)  |  Code Quality (20%)  |  Frontend (15%)  |  Documentation (15%)  |  Demo & Submission (10%)"),
spacer(200),
h1("2. Project Scope & Objectives"),
h2("2.1 In-Scope"),
bullet("Parsing and chunking the AWS Customer Agreement PDF"),
bullet("Generating vector embeddings and storing them in an in-process vector store (FAISS or ChromaDB)"),
bullet("Answering user queries via top-k retrieval + LLM generation"),
bullet("Returning both the generated answer and the source chunk(s) used"),
bullet("Graceful handling of unanswerable / out-of-scope queries — model must say so explicitly, not hallucinate"),
bullet("Logging every query-answer interaction to a SQL table with metadata"),
bullet("Analytics endpoint exposing aggregated query statistics via SQL GROUP BY / COUNT / AVG"),
bullet("Frontend UI: chat interface + analytics view"),
bullet("A public GitHub repository with a working README and a 2–3 minute demo video/GIF"),
spacer(80),
h2("2.2 Out-of-Scope"),
bullet("Multi-document ingestion (only the AWS Customer Agreement is used)"),
bullet("User authentication / multi-tenancy"),
bullet("Cloud hosting or containerisation (Docker optional; not required)"),
bullet("Paid API usage is not required — free-tier and local models are fully acceptable"),
spacer(200),
h1("3. System Architecture"),
h2("3.1 High-Level Architecture"),
body("The system follows a clean three-tier architecture where components communicate over HTTP. The Streamlit (or React) frontend communicates exclusively with the FastAPI backend. The backend orchestrates the RAG pipeline and persists logs to a SQL database."),
spacer(120),
infoBox("ARCHITECTURE FLOW","User → Frontend (Streamlit / React)  →  FastAPI Backend (Python)  →  [Vector Store · LLM API · SQLite/PostgreSQL]"),
spacer(120),
h2("3.2 Component Breakdown"),
twoCol([["COMPONENT","RESPONSIBILITY"],["PDF Ingestion","Parse the AWS Customer Agreement, split into overlapping text chunks"],["Embedding Engine","Convert each chunk to a dense vector (sentence-transformers / OpenAI / HuggingFace)"],["Vector Store","Persist and query chunk embeddings (FAISS or ChromaDB — in-process, no separate host)"],["RAG Query Engine","Retrieve top-k relevant chunks for a user query, construct a prompt, call the LLM"],["LLM Provider","Generate the final answer (OpenAI API / HuggingFace Inference API / Ollama local model)"],["FastAPI Server","Expose /ingest, /ask, /analytics endpoints; validate input/output with Pydantic"],["SQL Logger","Write one row per query interaction to the logs table; power analytics queries"],["Frontend","Chat UI (ask questions, display answer + sources) and analytics dashboard view"]]),
spacer(200), new Paragraph({children:[new PageBreak()]}),
h1("4. RAG Pipeline — Detailed Requirements"),
h2("4.1 PDF Ingestion"),
body("The system must parse the provided AWS Customer Agreement PDF and prepare it for embedding. The following requirements apply:"),
spacer(60),
bullet("Use PyMuPDF (fitz), pdfplumber, or pypdf for text extraction."),
bullet("Strip headers, footers, and page numbers that do not contribute semantic content."),
bullet("Preserve section headings and paragraph structure to maximise retrieval coherence."),
bullet("The ingestion process is triggered by calling POST /ingest."),
bullet("The system must return a 409 error if ingestion is attempted while an existing index is already loaded (or accept a force=true flag to re-ingest)."),
spacer(120),
h2("4.2 Chunking Strategy"),
body("Chunking is a critical design decision and must be justified in the README. The recommended approach:"),
spacer(60),
twoCol([["PARAMETER","RECOMMENDED VALUE & RATIONALE"],["Chunk Size","500–600 tokens — large enough for complete legal clauses; small enough to stay within embedding model context limits"],["Chunk Overlap","80–100 tokens (~15–20%) — prevents important boundary information from being missed"],["Splitter","RecursiveCharacterTextSplitter (LangChain) or equivalent, splitting on paragraph boundaries first, then sentences"],["Metadata","Each chunk must carry: chunk_id, source_page, section_header (if extractable), char_start, char_end"]]),
spacer(120),
h2("4.3 Embedding"),
bullet("Candidate libraries: sentence-transformers (all-MiniLM-L6-v2 for free/local), OpenAI text-embedding-3-small, or HuggingFace Inference API."),
bullet("Embed all chunks at ingest time and persist the index to disk so the server does not need to re-embed on restart."),
bullet("Document your chosen model and dimensionality in the README."),
spacer(120),
h2("4.4 Vector Store"),
bullet("Supported options: FAISS (faiss-cpu) or ChromaDB — both are in-process; no separate server required."),
bullet("The index must be serialisable (save/load from disk)."),
bullet("At startup, load the index if it exists; otherwise return a 503 on /ask with the message \"Document not yet ingested — call POST /ingest first.\""),
spacer(120),
h2("4.5 Retrieval"),
twoCol([["PARAMETER","REQUIREMENT"],["Top-k","k = 4 (default; configurable via environment variable TOP_K). Justify this value in the README."],["Similarity Metric","Cosine similarity (default for most vector stores)"],["Score Threshold","Optional: filter out chunks below a minimum cosine similarity (e.g., 0.3)"],["Returned Fields","Each retrieved chunk must include: chunk_text, chunk_id, source_page, similarity_score"]]),
spacer(120),
h2("4.6 Prompt Construction"),
body("The prompt sent to the LLM must follow a strict template to minimise hallucination:"),
spacer(60),
infoBox("REQUIRED PROMPT TEMPLATE STRUCTURE","System: You are an expert legal assistant. Answer the user's question using ONLY the provided context. If the answer is not present in the context, respond exactly with: \"I could not find this information in the AWS Customer Agreement.\"\n\nContext:\n[Chunk 1 text]\n---\n[Chunk 2 text]\n...\n\nQuestion: {user_query}\n\nAnswer:"),
spacer(80),
bullet("The LLM must never fabricate information not in the retrieved chunks."),
bullet("The phrase \"I could not find this information in the AWS Customer Agreement.\" must be the exact response for out-of-scope queries."),
spacer(120),
h2("4.7 Answer Hallucination Guard"),
body("Before returning the answer, the system should check whether the LLM response contains the no-answer phrase. If so:"),
bullet("Set answer_found = false in the response payload."),
bullet("Log the query with answer_found = 0 in the SQL table (used for analytics)."),
bullet("Still return HTTP 200 — this is a valid use case, not an error."),
spacer(200), new Paragraph({children:[new PageBreak()]}),
h1("5. SQL Logging & Analytics"),
h2("5.1 Database"),
bullet("Primary: SQLite (rag_logs.db) — sufficient for this assignment and zero-dependency."),
bullet("Optional: PostgreSQL if the candidate prefers (must be documented in README)."),
bullet("The database and schema must be created automatically on first run."),
spacer(120),
h2("5.2 Logs Table Schema"),
body("Every call to POST /ask must insert one row into the following table:"),
spacer(80),
schemaTable([["Column","Type","Required","Description"],["id","INTEGER PK","YES","Auto-increment primary key"],["query","TEXT","YES","The raw user question as submitted"],["answer","TEXT","YES","The full LLM-generated answer text"],["answer_found","BOOLEAN (0/1)","YES","1 if answer was found in context, 0 if the no-answer phrase was returned"],["source_chunks","TEXT (JSON)","YES","JSON array of retrieved chunk IDs and page numbers"],["latency_ms","REAL","YES","Wall-clock time in milliseconds from query receipt to response"],["model_used","TEXT","YES","Name/version of the LLM used"],["embedding_model","TEXT","NO","Name of the embedding model"],["top_k","INTEGER","YES","The value of k used for this retrieval"],["created_at","DATETIME","YES","UTC timestamp (DEFAULT CURRENT_TIMESTAMP)"]]),
spacer(120),
h2("5.3 Required Analytics Queries"),
body("The GET /analytics endpoint must execute and return the results of at least the following SQL queries:"),
spacer(80),
twoCol([["METRIC","SQL DESCRIPTION"],["Most Frequent Questions","SELECT query, COUNT(*) AS frequency FROM query_logs GROUP BY query ORDER BY frequency DESC LIMIT 10"],["Unanswerable Queries","SELECT query, created_at FROM query_logs WHERE answer_found = 0 ORDER BY created_at DESC LIMIT 20"],["Average Response Latency","SELECT AVG(latency_ms), MIN(latency_ms), MAX(latency_ms) FROM query_logs"],["Answer Found Rate","SELECT ROUND(100.0 * SUM(answer_found) / COUNT(*), 2) AS answer_rate_pct FROM query_logs"],["Query Volume by Hour","SELECT strftime('%H', created_at) AS hour, COUNT(*) FROM query_logs GROUP BY hour ORDER BY hour"]]),
spacer(120),
h2("5.4 Seed Data Requirement"),
infoBox("IMPORTANT — MINIMUM QUERY LOG REQUIREMENT","The candidate must run at least 30 test queries against the live /ask endpoint before submission. The mix must include genuine answerable questions AND at least 5 out-of-scope / irrelevant questions to populate the answer_found = 0 rows.","FEF3C7","92400E"),
spacer(200), new Paragraph({children:[new PageBreak()]}),
h1("6. FastAPI Backend"),
h2("6.1 Endpoint Specifications"),
spacer(80),
endpointTable([["METHOD","ENDPOINT","DESCRIPTION"],["POST","/ingest","Triggers PDF parsing, chunking, embedding, and vector index creation. Returns chunk count and status."],["POST","/ask","Accepts a user query, runs the full RAG pipeline, logs the interaction to SQL, and returns the answer + source chunks + metadata."],["GET","/analytics","Executes all analytics SQL queries and returns aggregated results as a structured JSON object."]]),
spacer(120),
h2("6.2 POST /ingest"),
h3("Request Body"),
code('{ "force": false }   // Optional. If true, re-ingest even if index already exists.'),
spacer(60),
h3("Success Response (200)"),
code('{ "status": "success", "chunks_created": 142, "embedding_model": "all-MiniLM-L6-v2", "message": "Index built and saved to disk." }'),
spacer(60),
h3("Error Responses"),
bullet("409 Conflict — Index already exists and force=false"),
bullet("500 Internal Server Error — PDF not found at configured path"),
spacer(120),
h2("6.3 POST /ask"),
h3("Request Body (Pydantic Model)"),
code('{ "query": "What are the termination rights under the AWS Customer Agreement?" }'),
spacer(60),
h3("Validation Rules"),
bullet("query must be a non-empty string (min length: 3 characters)."),
bullet("Return 422 Unprocessable Entity for empty or missing query."),
bullet("Return 503 Service Unavailable if the vector index has not been built yet."),
spacer(60),
h3("Success Response (200)"),
code('{ "query": "What are the termination rights...", "answer": "Either party may terminate...", "answer_found": true, "sources": [{ "chunk_id": "chunk_042", "page": 4, "text_snippet": "...", "similarity_score": 0.87 }], "latency_ms": 1243.5, "model_used": "gpt-4o-mini" }'),
spacer(120),
h2("6.4 GET /analytics"),
h3("Response Structure"),
code('{ "total_queries": 45, "answer_found_rate_pct": 82.2, "avg_latency_ms": 1102.4, "min_latency_ms": 430.1, "max_latency_ms": 3800.0, "top_queries": [...], "unanswerable_queries": [...], "queries_by_hour": [...] }'),
spacer(120),
h2("6.5 Error Handling Requirements"),
body("All error responses must be structured JSON — never raw Python stack traces."),
twoCol([["HTTP STATUS","WHEN TO RETURN"],["400 Bad Request","Malformed request body"],["422 Unprocessable Entity","Pydantic validation failure"],["503 Service Unavailable","Vector index not yet built"],["409 Conflict","POST /ingest called when index already exists and force=false"],["500 Internal Server Error","Unexpected exception — catch all, log traceback, return generic error"]]),
spacer(200), new Paragraph({children:[new PageBreak()]}),
h1("7. Frontend Dashboard"),
h2("7.1 Technology Choice"),
body("The candidate may choose either of the following frameworks:"),
spacer(80),
twoCol([["OPTION","NOTES"],["Streamlit","Runs as a separate process from FastAPI. Uses requests library to call FastAPI endpoints."],["React / Next.js","Fetches FastAPI endpoints via fetch() or axios. CORS must be configured."]]),
spacer(120),
h2("7.2 Required UI Views"),
h3("View 1: Chat Interface"),
bullet("Text input field for the user's question."),
bullet("Submit button (or Enter key) that calls POST /ask."),
bullet("Display the answer in a readable card/bubble format."),
bullet("Below the answer, display the source chunk(s): page number, similarity score, and a text snippet."),
bullet("If answer_found = false, display a clear notice."),
bullet("Show a loading indicator while the request is in flight."),
bullet("Error messages from the API must be displayed gracefully."),
spacer(80),
h3("View 2: Analytics Dashboard"),
bullet("A button or tab to switch to the analytics view."),
bullet("Calls GET /analytics on load."),
bullet("Display the following widgets:"),
bullet("Total queries and answer found rate.",1),
bullet("Average / min / max response latency.",1),
bullet("Top 10 most frequent questions.",1),
bullet("List of unanswerable queries.",1),
bullet("Query volume by hour.",1),
bullet("A Refresh button to reload analytics data."),
spacer(120),
h2("7.3 Non-Functional UI Requirements"),
bullet("Evaluation is on functional integration and clarity, NOT visual design polish."),
bullet("All API calls must handle loading and error states."),
bullet("The frontend must work with no manual configuration beyond what is in the README."),
spacer(200), new Paragraph({children:[new PageBreak()]}),
h1("8. Code Quality & Project Structure"),
h2("8.1 Required Project Structure"),
code("rag-qa-system/"),
code("├── backend/"),
code("│   ├── main.py"),
code("│   ├── rag/"),
code("│   │   ├── ingestor.py"),
code("│   │   ├── embedder.py"),
code("│   │   ├── vector_store.py"),
code("│   │   └── retriever.py"),
code("│   ├── llm/"),
code("│   │   └── generator.py"),
code("│   ├── db/"),
code("│   │   ├── models.py"),
code("│   │   └── logger.py"),
code("│   ├── schemas.py"),
code("│   ├── config.py"),
code("│   └── requirements.txt"),
code("├── frontend/"),
code("│   ├── app.py"),
code("│   └── requirements.txt"),
code("├── data/"),
code("│   └── aws_customer_agreement.pdf"),
code("├── .env.example"),
code("├── README.md"),
code("└── demo.gif"),
spacer(120),
h2("8.2 Code Standards"),
bullet("Every function and class must have a docstring."),
bullet("No spaghetti logic — each module has a single responsibility."),
bullet("Use type hints throughout (Python 3.10+)."),
bullet("Environment variables must be loaded from .env via python-dotenv."),
bullet("An .env.example file with all required keys must be committed."),
bullet("The codebase must not print raw stack traces to the user."),
spacer(200), new Paragraph({children:[new PageBreak()]}),
h1("9. README Requirements"),
h2("9.1 Required Sections"),
body("The README.md must contain all of the following sections:"),
spacer(80),
numbered("Project Overview — one paragraph describing what the system does."),
numbered("Architecture Diagram — ASCII or embedded image."),
numbered("Prerequisites — Python version, Node version (if React)."),
numbered("Installation — step-by-step commands."),
numbered("Configuration — full .env setup with descriptions."),
numbered("Running the Application — exact commands to start everything."),
numbered("API Reference — brief description of each endpoint with example curl commands."),
numbered("Design Decisions — explain chunking strategy, top-k value, embedding model, LLM provider."),
numbered("Assumptions — any assumptions made beyond the task description."),
numbered("Demo — embedded GIF or link to video (2–3 minutes)."),
spacer(120),
h2("9.2 README Quality Checklist"),
infoBox("THE TEST: A REVIEWER MUST BE ABLE TO CLONE THE REPO AND RUN THE APP USING ONLY THE README","Every command must be copy-pasteable. Every environment variable must be listed. Every dependency must be installable from the provided requirements.txt.","FEF3C7","92400E"),
spacer(200),
h1("10. Deliverables Checklist"),
twoCol([["DELIVERABLE","ACCEPTANCE CRITERIA"],["Public GitHub Repository","Publicly accessible. Contains all source code, .env.example, README.md, and demo. No API keys committed."],["FastAPI Backend","All three endpoints operational. Pydantic validation. Proper HTTP error codes."],["RAG Pipeline","PDF parsed and chunked. Embeddings stored. Top-k retrieval works. No-answer case handled."],["SQL Logging","Every /ask call logged. Schema matches specification. At least 30 rows seeded."],["Frontend","Chat interface and analytics view both functional. Loading and error states handled."],["README","All 10 required sections present. Clone-to-run works from README alone."],["Demo Video/GIF","2–3 minutes. Shows asking a question, viewing answer + sources, viewing analytics."],["Design Justification","README justifies chunk size, overlap, top-k, embedding model, and LLM provider."]]),
spacer(200), new Paragraph({children:[new PageBreak()]}),
h1("11. Evaluation Criteria"),
evalTable([["Category","Weight","What Evaluators Are Looking For"],["RAG Pipeline Design","20%","Chunking strategy with justified parameters, retrieval relevance, prompt construction quality, hallucination guard"],["FastAPI Backend & SQL","20%","Clean endpoint design, complete Pydantic models, correct HTTP error codes, well-designed SQL schema"],["Code Quality & Structure","20%","Modular project layout, docstrings, meaningful names, type hints, no hard-coded secrets"],["Frontend Integration","15%","Correctly consuming all three endpoints; loading and error states handled"],["Documentation (README)","15%","Setup instructions that work end-to-end; architecture overview; design decisions justified"],["Demo & Submission Hygiene","10%","Working 2–3 minute demo; clean public GitHub repo; no committed secrets"]]),
spacer(200),
h1("12. Constraints & Logistics"),
twoCol([["CONSTRAINT","DETAIL"],["Submission Deadline","48 hours from receipt of the task assignment"],["API Cost","No paid API required. Free-tier options are fully acceptable."],["Vector Store Hosting","No hosted vector database required. FAISS and ChromaDB run in-process."],["Database","SQLite is sufficient. PostgreSQL is optional."],["Originality","All code must be the candidate's own work."],["Language","Python (backend). Python (Streamlit) or JS/TS (React/Next.js) for frontend."],["Minimum Python Version","Python 3.10+"]]),
spacer(200),
h1("13. Design Decisions — Required Documentation"),
body("The following design choices must each be explicitly justified in the README."),
spacer(80),
h2("13.1 Chunking Strategy"),
infoBox("REQUIRED JUSTIFICATION","State the chunk size, the overlap amount, the splitting algorithm used, and explain WHY these values were chosen for the AWS Customer Agreement specifically."),
spacer(120),
h2("13.2 Top-k Choice"),
infoBox("REQUIRED JUSTIFICATION","State the value of k and explain the trade-off: too small → miss relevant context; too large → dilute the prompt with noise."),
spacer(120),
h2("13.3 Embedding Model"),
infoBox("REQUIRED JUSTIFICATION","State which embedding model was chosen and justify: dimension size, speed vs. quality trade-off, cost, and suitability for legal document retrieval."),
spacer(120),
h2("13.4 LLM Provider"),
infoBox("REQUIRED JUSTIFICATION","State which LLM was used and justify the choice: cost, latency, quality for Q&A tasks, and availability within the 48-hour timeframe."),
spacer(200),
divider(),
spacer(120),
new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "END OF PRODUCT REQUIREMENTS DOCUMENT", size: 20, color: C.lgray, font: "Arial", bold: true })], spacing: { before: 0, after: 40 } }),
new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Version 1.0  ·  RAG-Based Document Q&A System  ·  Vestaff Assignment  ·  June 2026", size: 18, color: C.lgray, font: "Arial", italics: true })], spacing: { before: 0, after: 0 } }),
];};
